### ISSUE TITLE
Make sure npm package works properly

### ISSUE THREAD

**Issue by Oferlis** [sharkio-dev/sharkio#123]
The info in npm site is not up to date. We should update it to reflect the current readme.

Also - when trying to install sharkio via npm using the command in the documentation  I got the following error: 
![Screenshot 2023-07-19 at 11 00 38](https://github.com/idodav/sharkio/assets/62609377/6b1da16d-c331-4beb-a93c-116e2e95dd93)

**Comment by idodav** [comment]
I can add maintainers to the npm package.
Write your npm usernames below and i'll add them to the npm package.

**Comment by idodav** [comment]
Also you the package is not sharkio.

It's @idodav/sharkio

**Comment by Oferlis** [comment]
my npm username is oferlis

**Comment by galeindor** [comment]
> I can add maintainers to the npm package. Write your npm usernames below and i'll add them to the npm package.

this fixed the problem for me , you should change the README to match the correct npm package name
