### ISSUE TITLE
Feature: mock response selection algorithms

### ISSUE THREAD

**Issue by idodav** [sharkio-dev/sharkio#131]
Allow differrent modes of mock version selection. 
1. Random - Choose a random response from the list of available mock responses
2. Sequence - Choose responses in a sequential order
3. Default only - return only the default response
4. ratio - give percentage to each response and return according to this
5. smart mock - switch case to decide which body to return based on simple logic(if else)

https://en.wikipedia.org/wiki/Strategy_pattern

use the strategy pattern to select the algorithm

**Comment by idodav** [comment]
Each mock will be able to hold mutiple responses.(currently we have only 1 response)

I want to have an algorithm/algorithms
that for every request will have different strategies for selecting which response to send back.

for example i have a mock:

/hello

responses:
1. 200 { "hello": "world1" } <- default
2. 200 { "hello": "world2" }
3. 500 { "goodbye": "world3" }

i want the mock manager to choose a different response for each sequencial request.

sequencial algorithm:
the first time i call the endpoint it will return 1st response. the second time 2nd response  etc..

random:
choose a random response for every request

default:
choose only the default response

**Comment by nkotzrenko** [comment]
@idodav I am taking this task
