### ISSUE TITLE
Tech: research and ingtegrate state management library for the dashboard

### ISSUE THREAD

**Issue by idodav** [sharkio-dev/sharkio#144]
Research modern state management libraries for react.
Decide which is the best for our project and implement it.

A few possibilities are:
https://github.com/pmndrs/zustand
https://mobx.js.org/README.html

**Comment by OshriAsulin** [comment]
Can i take this issue?

**Comment by idodav** [comment]
Assigned to you

**Comment by idodav** [comment]
@OshriAsulin Thank you very much for your contribution. And for researching several state management solution!

**Comment by idodav** [comment]
@OshriAsulin Thank you very much for your contribution. And for researching several state management solution!
