### ISSUE TITLE
Bug | openAPI is shown when service is deselected

### ISSUE THREAD

**Issue by Oferlis** [sharkio-dev/sharkio#167]
On openAPI page, when trying to create a new document, the API is shown only after selection and deselection of the service

**Expected behavior**
document should be shown/generated when the service is selected

**Screenshots**
![Screenshot 2023-07-30 at 15 27 00](https://github.com/idodav/sharkio/assets/62609377/75bb3173-1621-4bf1-9f10-5dcc4b9fe377)

**Comment by idodav** [comment]
Fixed in https://github.com/idodav/sharkio/pull/176
