### ISSUE TITLE
Add Dependabot 

### ISSUE THREAD

**Issue by SID262000** [sharkio-dev/sharkio#170]
https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

**Comment by idodav** [comment]
@SID262000 This is a great idea!

**Comment by SID262000** [comment]
I'll start working on this soon! Thanks @idodav for the go ahead

**Comment by idodav** [comment]
is this ready?

**Comment by SID262000** [comment]
@idodav I think I already created the codeql.yml which is the intended file for Depandabot
