### ISSUE TITLE
Root package.json warning

### ISSUE THREAD

**Issue by or-schneider** [sharkio-dev/sharkio#173]
**Describe the bug**
The root package.json shows a warning 'Matches a schema that is not allowed.'

**To Reproduce**
In a new clone, go to /package.json

**Expected behavior**
Package.json should not show have any warnings

**Screenshots**
![Code_nTkba30BOH](https://github.com/idodav/sharkio/assets/90090260/bac49ecf-d16d-4fc4-a418-a6283a0017b5)

**Additional context**
The warning happens because there can only be one 'bundledDependencies' field and we have two:
'bundledDependencies' and its deprecated form
'bundleDependencies'
See https://docs.npmjs.com/cli/v9/configuring-npm/package-json#bundledependencies

**Comment by or-schneider** [comment]
@idodav Should decide which field to keep
Bundle everything "bundledDependencies": true,
or bundle explicitly

**Comment by idodav** [comment]
@or-schneider decide on the one that you want. Assigned to you.

**Comment by idodav** [comment]
@shootermv fixed. Thank you very much.
