### ISSUE TITLE
Bug | Dark mode preference reset on refresh

### ISSUE THREAD

**Issue by Oferlis** [sharkio-dev/sharkio#194]
**Describe the bug**
Dark mode toggle resets on refresh of the page

**To Reproduce**

1. Toggle site to dark mode
2. Refresh the page

**Expected behavior**
An existing session should keep the user's preference

**Additional context**
Saving the preference to localStorage seems to be the solution.
https://dev.to/ayc0/light-dark-mode-avoid-flickering-on-reload-1567

**Comment by OshriAsulin** [comment]
Yes, I am on it @Oferlis

**Comment by OshriAsulin** [comment]
This issue fixed in #195 pr
