### ISSUE TITLE
UI Bug Triggering Error in DevTools Console on Sidebar Button Interaction

### ISSUE THREAD

**Issue by OshriAsulin** [sharkio-dev/sharkio#198]
**Issue Description**:
When interacting with the sidebar buttons in our application, a UI bug is consistently triggering an error in the browser's DevTools console. This issue has been observed each time a different sidebar button is clicked, resulting in a suboptimal user experience and potential functionality problems.

**Steps to Reproduce**:

- Open the application.
- Navigate to the sidebar.
- Click on any sidebar button.

**Expected Behavior**:
The application should respond to the button click without any errors in the console.

**Sidebar UI Bug and Error Demonstration:**

https://github.com/sharkio-dev/sharkio/assets/114335827/2fb624e9-38cd-4ef8-b2d2-eeb5a6ccd42c

**Comment by vishesh-hue** [comment]
i can handle this

**Comment by OshriAsulin** [comment]
> i can handle this

@idodav ?

**Comment by idodav** [comment]
> i can handle this

Awesome!!
Assigning this to you

**Comment by OshriAsulin** [comment]
It doesn't fixed yet

@idodav  Can he work on this issue?

**Comment by AliYar-Khan** [comment]
facing issue while trying to run on local, @OshriAsulin @idodav any docs for running it on local environment ?

**Comment by idodav** [comment]
> facing issue while trying to run on local, @OshriAsulin @idodav any docs for running it on local environment ?

There are docs. But we now use supabase and you need the env vars. I'll dm them to you. If you know of a solution for this let me know!

**Comment by idodav** [comment]
> It doesn't fixed yet
> 
> @idodav  Can he work on this issue?

yes I'll assign this!

**Comment by AliYar-Khan** [comment]
@idodav please share the env vars so that i can start working on this !
