### ISSUE TITLE
bug: Incorrect use of 'class' instead of 'className' in React dashboard

### ISSUE THREAD

**Issue by OshriAsulin** [sharkio-dev/sharkio#211]
Description:
The issue occurs in the React dashboard where the 'class' attribute is incorrectly used instead of the 'className' attribute. This is causing unexpected behavior.

Expected behavior:
I expected that the 'className' attribute would be used to apply CSS classes to elements in the React dashboard, as is the standard practice in React.

The URL for this bug-
https://github.com/sharkio-dev/sharkio/blob/main/traffic-dashboard/src/components/navbar/navbar.tsx

**Comment by idodav** [comment]
@OshriAsulin thanks for the PR!!
