### ISSUE TITLE
change project icon to something more simple, without background

### ISSUE THREAD

**Issue by shootermv** [sharkio-dev/sharkio#218]
Currently shark icon has a background

It better to be without background

Also - usually logo icon is something simple, like:
![image](https://github.com/sharkio-dev/sharkio/assets/1336862/75f8698f-dfe4-402f-a403-cdaf3f2eb774)

**Comment by nakel-ola** [comment]
Something like this
![138167475](https://github.com/sharkio-dev/sharkio/assets/109567025/6c42f3aa-d8c0-48ba-b0e4-d543f7b4595e)

**Comment by shootermv** [comment]
exactly! only it may be good to a have a version of logo with different color than white (because white cannot be visible at bright background)
