### ISSUE TITLE
for simplicity: replace directory names to be `client` & `server`

### ISSUE THREAD

**Issue by shootermv** [sharkio-dev/sharkio#223]
**Describe the bug**
for simplicity: replace directory names to be `client` & `server` (instead of `traffic-sniffer` and `traffic-dashboard`)

**Comment by Sushannt** [comment]
please assign this to me.

**Comment by idodav** [comment]
@Sushannt assigning this to you!

**Comment by idodav** [comment]
Thanks you @Sushannt merged your PR. 
And thank you @shootermv for suggesting this change!
