### ISSUE TITLE
Feature: Create a cli tool that executes requets

### ISSUE THREAD

**Issue by idodav** [sharkio-dev/sharkio#30]

**Comment by hadar-hezi** [comment]
Please assign hadar-hezi

**Comment by idodav** [comment]
Build a class in python with the following interface:

listRequests - return all the available requests
addRequest - (method,path,parmeters,body)
removeRequest - (method,path,parmeters,body)
execute - (requestId)

interactive - 
Chat:
which request do you want to run?
1. /sharkio/sniffer/action/getMocks
2. /sharkio/sniffer/:port/mock

asnwer: 2

Please enter port number:
5020

succes/fail
