### ISSUE TITLE
Allow copy code snippet with cursor

### ISSUE THREAD

**Issue by Tamir198** [sharkio-dev/sharkio#358]
Right now on the website under getting started If I want to copy a text I can do it via the copy button: 

![image](https://github.com/sharkio-dev/sharkio/assets/34707669/ebfca62c-977b-4e44-a866-39a3b0266a54)

It would be nice if we could copy the text by marking it with the mouse as well, for example: 

![image](https://github.com/sharkio-dev/sharkio/assets/34707669/8971112c-a461-450c-af5a-b93032b03746)

**Comment by idodav** [comment]
Thanks Tamir. We need to rewrite the documentation section anyway :)
But it's a very good suggestion.
