### ISSUE TITLE
Feature: Save requests to a json file

### ISSUE THREAD

**Issue by idodav** [sharkio-dev/sharkio#39]
Use https://www.npmjs.com/package/node-json-db to save the requests data to a local file.

Every time a request is intercepted here:
https://github.com/idodav/sharkio/blob/96618aceebb231fd978697c89e15f15bff9898aa/traffic-sniffer/lib/request-metadata/path-metadata.ts#L36-L52

update the database.

**Comment by shravan20** [comment]
@idodav: I would like to pick this issue

**Comment by idodav** [comment]
@shravan20 I wanted a quick solution to persist the data locally. Without additional setup of mongo/database.
We can explore other options if you have something in mind.
