### ISSUE TITLE
Feature: landing page

### ISSUE THREAD

**Issue by idodav** [sharkio-dev/sharkio#4]
Create a landing page for the product.

**Comment by idodav** [comment]
Bought a domain sharkio.dev

**Comment by idodav** [comment]
@noams24 Hi Noam did you get any progress with this?

**Comment by noams24** [comment]
Not yet, Do you want me to create a Figma design? @idodav

**Comment by idodav** [comment]
Started worling on a landing page:

https://sharkio.webflow.io/

**Comment by idodav** [comment]
examples of open source landing pages:
https://novu.co/
https://nocodb.com/

**Comment by idodav** [comment]
done in https://sharkio.dev/getting-started.
It will need more design work but it's ok for now.
