### ISSUE TITLE
Feature: Generate request code for other languages

### ISSUE THREAD

**Issue by shravan20** [sharkio-dev/sharkio#83]
As we support curl command as sample for the preview, for the user to copy and paste and run. Similarly we should provide support multiple other languages as well using native libraries:
- JavaScript [using `Fetch`]
- Nodejs [using `axios` / `node-fetch`]
- Python [using `requests`] 
- Java [using `OkHttp`]
- C/C++ [using `libcurl`]
- Go [using `Native`]
- PHP [using `Guzzie/curl`] 

Select of language could be preview as a drop down option

![image](https://github.com/idodav/sharkio/assets/47430686/893a11dd-12e0-431b-b7d4-6fd14799c9de)

**Comment by Alon2904** [comment]
Can you please provide more information about this issue? 
Where can those examples be found?
