### ISSUE TITLE
Tech: Add Global Error Handler at controller layer

### ISSUE THREAD

**Issue by shravan20** [sharkio-dev/sharkio#86]
Description:

Currently we are handling the errors at each controller layer, instead move it to separate layer say a callback layer, which checks if its success or failure and accordingly wraps it into a valid response container.

If anyone else wants to pick up, please comment tagging @idodav or @shravan20 , can be re-assigned

**Comment by idodav** [comment]
You could checkout [express promise router](https://www.npmjs.com/package/express-promise-router)

**Comment by giladfuchs** [comment]
can I take this issue?
